### ISSUE TITLE
Добавить выпадающее меню при наведении на строки сверху (где логотипы игр и кнопки Главная, Новости, Статьи)

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#10]
При наведении на логотип сверху появляется название игры, помимо этого должно появляться ещё и список категорий соответствующей игры из меню геймеру почитать, а при наведении на группу справа должен появляться ещё один список статей с соответствующими статьями (из этой категории).
Аналогично должны появляться выпадающие меню при наведении на "кнопки" над строкой с играми (я про главная, новости, статьи, конкурсы, форум).
При наведении на главную следующие варианты: вернутся на главную, выбрать игру, почитать статьи, почитать новости, посмотреть результаты/ самому поучаствовать в конкурсах, почитать форум.

**Comment by simlex-titul2005** [comment]
При наведении на главную следующие варианты: вернутся на главную, выбрать игру, почитать статьи, почитать новости, посмотреть результаты/ самому поучаствовать в конкурсах, почитать форум.
это сделал... А остальное актуально? Есть же уже блоки по категориям

**Comment by EugeneKormin** [comment]
По этому пока все
