### ISSUE TITLE
Сделать свой информер афоризмов и добавить его в текст справа, над блоком "Интересные ссылки"

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#111]

**Comment by simlex-titul2005** [comment]
Более подробнее опиши, что такое аффоризмы, нужен ли функционал (и какой) для их добавления в админке и все такое

**Comment by EugeneKormin** [comment]
аффоризмы - забавные, остроумные, короткие выражения, пользователь может менять на новый и оценивать предыдущий (понравилось/не понравилось). Функционал скорее, нет. Их нужно загрузить один раз и все. Пока так. Но это не приоритетная задача. Сейчас не нуно тратить время на ее решение

**Comment by EugeneKormin** [comment]
я нашел источник афоризмов и фраз для информера:
https://twitter.com/Film_quotes__?cn=ZmxleGlibGVfcmVjc18y&refsrc=email
https://twitter.com/literabook?cn=ZmxleGlibGVfcmVjc18y&refsrc=email
