### ISSUE TITLE
Изменить кнопки для возвращения на главную после статьи/новости, добавить кнопки после статьи

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#12]
Добавить цвет (#E6D891). При нажатии на любую из кнопок появляется два выпадающих меню (справа и слева). 
Слева. "Мне понравилась статья, дочитаю", При наведении появляется выпадающее меню с причиной почему: 
- то, что искал, автор хорошо пишет, 
- новость/статья интересная, 
- хороший ресурс 
(должна быть возможность выбрать несколько вариантов. 
Справа "Это не то, что я искал". При наведении появляется выпадающее меню с причиной почему: 
- не то, что искал, 
- автор плохо пишет, 
- новость/статья неинтересная, 
- плохой ресурс, разочарован (должна быть возможность выбрать несколько вариантов). 
Сделать видимый подсчет с одной стороны, сколько сказали, что статья хорошая, сколько с другой - сколько сказали, что статья плохая и продолжили поиск, через "/", сколько ушли. 

Дополнительно на новостные тексты добавить: Новость актуальна, новость неактуальна. 

Добавить кнопку: "Хочу прочитать продолжение". Появляются Подписаться/не подписывать. Соответственно, реализуем только после добавления возможности подписки

**Comment by simlex-titul2005** [comment]
Какую новость считать актуальной, какие критерии?

**Comment by EugeneKormin** [comment]
это уже пользователь сам решит актуально или нет. Ему нужно дать такую возможность

**Comment by simlex-titul2005** [comment]
Я про это: Дополнительно на новостные тексты добавить: Новость актуальна, новость неактуальна. 
или это должны быть кнопки?

**Comment by EugeneKormin** [comment]
да

**Comment by simlex-titul2005** [comment]
Актуальна еще задача? может дополнить что-то?

**Comment by EugeneKormin** [comment]
Пока не нужно делать, я напишу другой issue
