### ISSUE TITLE
Динамические блоки в статьи

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#131]
1) добавлять блок с "предыдущей новостью и следующей новостью" по игре или категории прямо в тело новости, справа от твиттера и список из 6 последних новостей из каждой категории в столбик под ним;
2) текст статьи смотрится совсем сиротливо. Модно добавить блок из 4-ех самых расшариваемых статей. Если таких нет, то из комментируемых, лайкнутых, просмотренных (порядок имеет значение).
Не знаю, возможно будет грузить сайт, но было бы хорошо, если бы можно отдельно было бы выводить 3 за определенный период: за час, день, месяц, квартал, полугодие, год, все время, а четвертую назвать самая актуальная статья и выводить по формуле: шар/кол-во часов.

**Comment by simlex-titul2005** [comment]
Первые два пункта сделал. Если что не так, открывай новые issue
