### ISSUE TITLE
добавить в шапку отредактированные статьи

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#144]

**Comment by simlex-titul2005** [comment]
Плиз, более подроднее.... Не перекликается с этим:https://github.com/EugeneKormin/Game-exe/issues/143
?

**Comment by EugeneKormin** [comment]
похоже, что нет, это функционал, который позволит выводить редактированные новости в шапку в зависимости от даты редактирования наряду с впервые опубликованными новостями

**Comment by simlex-titul2005** [comment]
Статьи там отображаться по этому алгоритму будут...
https://github.com/EugeneKormin/Game-exe/issues/104
Есть ли смысл отображать там отредактированные материалы?
