### ISSUE TITLE
Добавить ограничения для ввода метатегов:

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#145]
1. Title:
Наличие Title;
Уникальность Тitle;
Размер Тitle 7-15 слов.
2. H1:
Наличие H1;
Уникальность H1;
Размер 2 - 6 слов.
3. Keywords:
Наличие Keywords;
Уникальность Keywords;
Размер менее 20 фраз.
4. Description:
Наличие Description;
Уникальность Description;
Размер 150 - 700 знаков.
5. Теги к статьям и новостям: 4 слова, 650 символов.

**Comment by EugeneKormin** [comment]
[ограничения и принцип построения тегов и метатегов.xlsx](https://github.com/EugeneKormin/Game-exe/files/233259/default.xlsx)

**Comment by simlex-titul2005** [comment]
Сделал
