### ISSUE TITLE
Автоматически добавлять все метатеги к новым тегам.

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#155]
Например я написал новость про sdk3, тогда автоматически появляется статья все теги по sdk3. И для это статьи необходимо прописать description, keywords, h1, title.

**Comment by simlex-titul2005** [comment]
Более подробно нужно.... Это как?

**Comment by simlex-titul2005** [comment]
На автомате можно задать только title и h1 равные между собой. Остальное на автомате задать нельзя... Мы же не можем лингвистику программировать... смысла нет

**Comment by EugeneKormin** [comment]
Я к тому, что например, "страница про... " дальше название тега. - это keywords.
"На данной странице находятся статьи и новости связанные одним словом и это слово..." - это description. В шаблон останется вставить название тега.

**Comment by simlex-titul2005** [comment]
Это только для страниц облака тегов?

**Comment by EugeneKormin** [comment]
Да

**Comment by EugeneKormin** [comment]
Я не дописал, в моей голове это было очевидно, мой косяк...

**Comment by simlex-titul2005** [comment]
Сделал
