### ISSUE TITLE
Необходимо делить трафик переходящий по рекламным баннерам.

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#165]
Необходимо напротив каждого баннера добавить ссылки: "Мне интресно это предложение", "Не уверен", "Я только посмотрю". Смысл разделить на тех, кто хочет купить, кто не уверен хочет ли и на тех, кто хочет просто посмотреть.

Формулировка фраз дана для примера, интересно выслушать твои предложения по формулировке.

**Comment by simlex-titul2005** [comment]
Необходимо закрыть, вроде решили по этому?

**Comment by EugeneKormin** [comment]
Да
