### ISSUE TITLE
Спроси у диза сможет ли он поменять фон на коллаж в стиле картинок к статьям, ты говорил, он с фотошопом на "ты"

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#184]
![default](https://cloud.githubusercontent.com/assets/16157678/15450845/97c1742a-1fec-11e6-957c-a95682367164.jpg)
![default](https://cloud.githubusercontent.com/assets/16157678/15450846/9e3c9d70-1fec-11e6-946d-a916af80a555.jpg)
![default](https://cloud.githubusercontent.com/assets/16157678/15450848/a639e33e-1fec-11e6-9c9b-7fc9fd946885.jpg)
![default](https://cloud.githubusercontent.com/assets/16157678/15450844/8eb07b6a-1fec-11e6-81f3-4faf2f28a04e.jpg)

**Comment by EugeneKormin** [comment]
Фон сделал красным, чтоб дизу проще его было вырезать. 
![image](https://cloud.githubusercontent.com/assets/16157678/15451020/33acdf22-1ff3-11e6-83b0-223290a6fb2e.jpg)
Список категорий: 
![image](https://cloud.githubusercontent.com/assets/16157678/15451026/58a8be54-1ff3-11e6-9046-b1fb445b247f.png)
Может поменять фразы из соцсетей на Юмор и не только. К фразам из соцсетей у многих пренебрежительное отношение, может поменять на нейтральное, например: "Юмор и не только", мне кажется это "шарить больше будут".
Картинки будут только у фраз из фильмов, инфографик (там без картинок туго). Приеду домой (7.06.2016)  сниму видео о пасхалках, там не долго. Автор озвучит. Получается, нужно расшаривать либо видео, либо описание пасхалки словами?

**Comment by simlex-titul2005** [comment]
Актуально?

**Comment by EugeneKormin** [comment]
инфографикой займемся позже, сейчас это не приоритет
