### ISSUE TITLE
Местоположение и расположение рекламных блоков

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#193]
Размеры баннеров: 160х600, 240х400, 250х380, 300х250,  300х300, 728х90      
не размещать рядом с кнопками меню и соцкнопками      
добавить в описание к блоку фавиконку рекламодателя      
сделать три ссылки:      
1) Буду брать      
2) Буду думать      
3) Буду просто смотреть      
первая: переход на страницу оформления заказа      
вторая и третья: переход на Landing Page      
Места расположения:      
1) под шапкой на главной странице      
2) внутри страницы перед и после основного контента
3) в качестве теста можно добавить слева от блока геймеру почитать, есть исследования, которые говорят о положительной динамике, но мне сомнительно
исследования Яндекса и Гугла совпадают
личной статистики я не нашел (что не удивительно), в основном все перепечатывают оригинальные исследования
я еще вот о чем подумал, можно подумать над внедрением внутреннего поиска Яндекс и Гугл. При наведении на них добавлять запросы по которым сайт явном топе, хотя как к этому отнесется сами ПС - вопрос.
Яндекс - непредсказуем, он может посчитать, что это "манипуляция выдачей!
выдачей"
![default](https://cloud.githubusercontent.com/assets/16157678/15592079/39bc3b8e-23e4-11e6-87c2-d2e84bf6a6e7.png)
![default](https://cloud.githubusercontent.com/assets/16157678/15592080/39c0113c-23e4-11e6-91fe-d1d08aedd483.jpg)
![default](https://cloud.githubusercontent.com/assets/16157678/15592081/39c3bdd2-23e4-11e6-96fb-3307eaebdb3b.png)
![default](https://cloud.githubusercontent.com/assets/16157678/15592082/39c86b52-23e4-11e6-880f-7bb675ca1807.png)
![ctr](https://cloud.githubusercontent.com/assets/16157678/15592083/39cc5e2e-23e4-11e6-87b9-1a1ec8cebe23.png)
нужно поэкспериментировать с фоном. Каждый баннер сделать в двух вариантах с полупрозрачным фоном и без него

![image](https://cloud.githubusercontent.com/assets/16157678/15592945/26fabba4-23eb-11e6-8e30-fc90043894d4.png)

**Comment by simlex-titul2005** [comment]
Блоки со временем проставяться на всех местах... просто говори, где поставить новый блок и все.
