### ISSUE TITLE
на странице вместо ошибка сервера писать: данный раздел сайта обновляется, зайдите через 15 минут и обратный отчёт

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#212]

**Comment by simlex-titul2005** [comment]
Я предлагаю сделать так:
1) Пишем "Непредвиденная ошибка сервера. Мы уже работаем над устранением причин"
2) заметная кнопка для отправки информации об ошибке на мыло

**Comment by EugeneKormin** [comment]
хорошо




С уважением, 
Евгений

**Comment by EugeneKormin** [comment]
хорошо




С уважением, 
Евгений

**Comment by simlex-titul2005** [comment]
Сделал
