### ISSUE TITLE
добавить версию игры (в реалиях какой версии написана новость или статья)

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#217]

**Comment by simlex-titul2005** [comment]
Это же можно прописать в самом материале, к какой версии он относиться. А версию задавать не нужно, она же меняется.

**Comment by EugeneKormin** [comment]
я к тому, что добавить на странице редактирования материала блок "Версия"

**Comment by simlex-titul2005** [comment]
Сделал, появиться после след. перезаливки сайта
