### ISSUE TITLE
Исключить повторение вопросов на сайте, по крайней мере, в рамках 1 сессии (по-другому не получится)

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#229]

**Comment by simlex-titul2005** [comment]
В рамках прохождения тестов вопросы не повторяются... Или есть где повторения?

**Comment by EugeneKormin** [comment]
в рамках 1 сессии- ,но если он захочет пройти еще раз

**Comment by simlex-titul2005** [comment]
если он захочет пройти еще раз - вопросы подставляются в случайном порядке. иначе придется запоминать все вопросы теста и все сессии пользователя для теста
