### ISSUE TITLE
Между результатами теста и кнопкой "попробовать снова" (заменить на посмотреть другие картинки танков) добавить блоки с...

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#230]
...юмором, статьями, новостями, другими тестами, афоризмами

**Comment by simlex-titul2005** [comment]
Блоки с последними материалами добавил

**Comment by EugeneKormin** [comment]
куда?
http://game-exe.com/articles/2016/10/12/glavnie-sobitiia-2015-goda#

**Comment by simlex-titul2005** [comment]
Добавил между результатами теста

**Comment by EugeneKormin** [comment]
может добавить возможность добавить добавлять блоки юмором, статьями, новостями, другими тестами, афоризмами, Прямо внутри текста, чтоб как-то разнообразить текст.

**Comment by simlex-titul2005** [comment]
на каких страницах?

**Comment by EugeneKormin** [comment]
на подобных: http://game-exe.com/articles/2016/10/12/glavnie-sobitiia-2015-goda#

**Comment by simlex-titul2005** [comment]
надо как-то это предствить, нарисуй схематично хотябы

**Comment by EugeneKormin** [comment]
хорошо, сюда скину
