### ISSUE TITLE
На страницу с юмором добавить кнопку развернуть, чтоб можно было дочитать шутки

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#231]
Мне самому интересно, чем некоторые закончились))

**Comment by simlex-titul2005** [comment]
Тогда не будут переходить на страницу с юмором, чтобы поделиться. Это специально сделано

**Comment by EugeneKormin** [comment]
Я не пойму, а как тогда делиться и узнавать окончание историй?

**Comment by simlex-titul2005** [comment]
Там есть кнопка поделиться

**Comment by EugeneKormin** [comment]
увидел
