### ISSUE TITLE
Отрисовать всплывающий pop-up для уточнения причины ухода с сайта

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#24]
Не нужно останавливать, нужно вежливо, в максимально простом дизайне, вежливо попросить уточнить причину ухода.

**Comment by simlex-titul2005** [comment]
Пользователей раздражают такие попапы. Единственная причина, при которой стоит показывать попам - это когда юзер редактирует какую-то инфу и, не заполнив все поля, уходит со страницы редактирования

**Comment by EugeneKormin** [comment]
тогда может сделать блок: на сайте мне не нравится и пользователи будут голосовать

**Comment by simlex-titul2005** [comment]
Можно сделать отдельный механизм голосования и провести через движок. Тема голосования и вопросы будут задаваться в админке. Как такой вариант?

**Comment by EugeneKormin** [comment]
ок
