### ISSUE TITLE
Добавить видео в категорию юмор

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#240]
чтобы запросы к api каждый раз не делать, необходимо данные закешировать, а то там ограничение на кол-во запросов стоит
http://game-exe.com/humor

**Comment by simlex-titul2005** [comment]
Добавить таймер, указывающий на дату следующего обновления видео

**Comment by simlex-titul2005** [comment]
Добавить специфичное место баннера для рекламы
