### ISSUE TITLE
Установить всплывающий pop-up при попытке уйти с сайта

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#25]
Собирать статистику с каких страниц уходили, кто ответил, кто нет
Необходимо завершение https://github.com/EugeneKormin/Game-exe/issues/24

**Comment by simlex-titul2005** [comment]
Попап раздражает пользователей. Может не стоит?

**Comment by EugeneKormin** [comment]
Хорошо
