### ISSUE TITLE
Сделать изменения

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#256]
Добавить 3 лучших видео вряд между каждым 5 афоризмом в категорию кратко (18 Short Movies)
Добавить 3 лучших видео вряд между каждым 3 тестом в категорию тесты (23 Comedy)
Между каждым третьим "элементом юмора"  добавить 3 видео вряд (справа убрать)
Убрать категорию Популярное

**Comment by simlex-titul2005** [comment]
Сделал
