### ISSUE TITLE
на главной странице поменять тесты:

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#264]
Убрать: Dota 2 в лицах, путеводный атлас жреца
Добавить: второе имя танка и сокращение в чате

**Comment by simlex-titul2005** [comment]
Тесты появляются в случайном порядке (3 штуки). Показывать или нет на главной - задается в админке

**Comment by EugeneKormin** [comment]
Показывать тесты в случайном порядке - не очень хорошая идея. В качестве теста можно, но сейчас лидеры уже есть, поэтому пока случайный порядок не нужен

**Comment by simlex-titul2005** [comment]
Ты можешь отрегулировать это числом показываемых тестов на главной странице - на данный момент их - 3 шт

**Comment by EugeneKormin** [comment]
Кол-во показов три. А почему нельзя задавать самостоятельно тесты на главной странице?
