### ISSUE TITLE
Подумать над оформлением видео

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#268]

**Comment by simlex-titul2005** [comment]
Предлагаю сделать отдельную страницу для просмотра видео (своего, по api запрашивать всю инфу о видео) и всплывающее окно для просмотра для чужого

**Comment by EugeneKormin** [comment]
Хорошая идея, оно странно смотрится и не вписывается в дизайн. Ты имеешь ввиду заменить видео на строку, при наведении на которую будет выпадать видео? Если да, то хорошая идея.

**Comment by simlex-titul2005** [comment]
нет, по нажатию на наше видео сайта происходит вызов api youtube и переход на страницу с данными по видео и плеером yt. при нажатии на стороннее видео (которое парсим с yt) происходит открытие модального окна с плеером

**Comment by EugeneKormin** [comment]
При нажатии на наше видео - переход на наш канал
При нажатии на чужое - открытие модального окна
Я правильно понимаю? Если да, то ок.

**Comment by simlex-titul2005** [comment]
при нажатии на наше видео - переход на страницу с видео на сайте
При нажатии на чужое - открытие модального окна

**Comment by EugeneKormin** [comment]
Видео будет делиться по категориям?

**Comment by simlex-titul2005** [comment]
Каким именно? на сайте нет категорий видео

**Comment by EugeneKormin** [comment]
Это ж наши видео... все правильно. Пусть будет так.

**Comment by EugeneKormin** [comment]
Так я же согласился с твоим предложением, что:
при нажатии на наше видео - переход на страницу с видео на сайте
При нажатии на чужое - открытие модального окна

**Comment by simlex-titul2005** [comment]
Модальное окно не нужно получается - так как это - дополнительные вызовы и к api и к сайту. Лучше пусть чужое видео открывается в новой вкладке с переходом на страницу видео в youtube

**Comment by EugeneKormin** [comment]
Хорошо

**Comment by simlex-titul2005** [comment]
И еще - видео будет считаться нашим, если привязано к материалу. Тогда для таких видео будет отдельная страница для просмотра открываться в новой вкладке. Но по факту там могут быть и видео не с канала сайта

**Comment by EugeneKormin** [comment]
Ничего страшного

**Comment by simlex-titul2005** [comment]
Сделал
