### ISSUE TITLE
Изменить вид текста

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#271]
![default](https://cloud.githubusercontent.com/assets/16157678/21466144/d6376a7c-ca12-11e6-9af6-6becd4b97a31.png)

**Comment by simlex-titul2005** [comment]
Это я оформлю как угодно когда будет что вставлять

**Comment by EugeneKormin** [comment]
Пока сделай как на картинке, ничего страшного, что нету инфографики, нужен белый фон под всем текстовым материалом. Короткие строки людям больше нравятся, хотя читают их как правило хуже...
P.s. дополни описание, как вставлять картинки, я все время забываю адрес, который надо вписывать.

**Comment by EugeneKormin** [comment]
Я понял как это делается, в случае необходимости попробуем автоматизировать, пока нет острой необходимости
