### ISSUE TITLE
Починить афоризмы

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#272]
Ускорить время "перемотки" афоризмов, при смене афоризма пользователь должен видеть афоризм, а не перематывать до него. В идеале, афоризм должен меняться на том же экране
Добавить возможность остановить "обратный отсчет"

**Comment by simlex-titul2005** [comment]
Сделал

**Comment by EugeneKormin** [comment]
![img_0526](https://cloud.githubusercontent.com/assets/16157678/21533028/54b21a18-cda2-11e6-9006-0920e2350032.PNG)
Теперь все пропало. Добавь кнопку: перейти на страницу афоризмов

**Comment by simlex-titul2005** [comment]
Нажми Ctrl+F5

**Comment by simlex-titul2005** [comment]
Кнопка называется "Комментировать, шарить, оценить". Она и является ссылкой на страницу афоризма

**Comment by EugeneKormin** [comment]
Через какое-то кол-во кликов таймер перестает работать
