### ISSUE TITLE
Добавить возможность расшаривания инфографик прямо из статьи

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#273]
Также добавить возможность ставить лайки, комментировать...

**Comment by simlex-titul2005** [comment]
Расшарить можно ссылку... Не понимаю, как ты хочешь расшарить инфографик

**Comment by EugeneKormin** [comment]
Также как расшаривания афоризмы

**Comment by simlex-titul2005** [comment]
Блин, я же пишу, расшаривать можно ссылку. Инфографик (картинка) - это ссылка? Есть для него страница?

**Comment by EugeneKormin** [comment]
Значит нужно для каждой инфографики динамически добавлять страницу, как для афоризмов. У афоризмов есть ведь своя страница, по тому же принципу она должна быть и у инфографик

**Comment by simlex-titul2005** [comment]
Получается так:

1. необходимо обрабатывать картинки для инфографиков как отдельную модель и в БД и в коде
2. в админке для материалов сделать дополнительную вкладку "Инфографики", на которой будут добавляться, редактироваться и удаляться картинки
3. инфографики будут вставляться в html материала в виде Bbcode (так же, как сейчас вставляются картинки)
4. разработать сдетализированную страницу инфографика (лайки, дизлайки, кнопки шар

**Comment by EugeneKormin** [comment]
да так

**Comment by simlex-titul2005** [comment]
Сделал
http://game-exe.com/articles/2016/12/23/vse-o-kibersporte-i-kak-v-nego-popast
Ctrl+F5 если что
