### ISSUE TITLE
Добавить картинки статей в блок статей

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#274]

**Comment by simlex-titul2005** [comment]
Приложи скрин - куда и что добавить

**Comment by EugeneKormin** [comment]
![default](https://cloud.githubusercontent.com/assets/16157678/21798142/0714e550-d767-11e6-9e2f-67b5420a03b0.png)

**Comment by simlex-titul2005** [comment]
А если нет главной картинки? Можно вставлять первый инфографик? А если нет инфографиков?

**Comment by simlex-titul2005** [comment]
Может так:
Если есть инфографики, вставлять первый инфографик, иначе - первую картинку, иначе - картинку по-умолчанию какую-нить
?

**Comment by simlex-titul2005** [comment]
Сделал
