### ISSUE TITLE
Ограничить теги к статьям/новостям 3-мя словами, если в теге больше слов, такие теги -удалить

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#277]

**Comment by simlex-titul2005** [comment]
Я бы вообще ограничил одним словом

**Comment by simlex-titul2005** [comment]
Сделал
В админке можно настроить ограничение на кол-во слов для тега

**Comment by EugeneKormin** [comment]
Можешь скинуть ссылку?

**Comment by simlex-titul2005** [comment]
Теги задаются на вкладке "Облако тегов" страницы редактирования материала
