### ISSUE TITLE
Добавить блок "подписаться" (нет вертикального и горизонтального шаблонов)

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#279]

**Comment by simlex-titul2005** [comment]
А где его разместить?

**Comment by EugeneKormin** [comment]
Хороший вопрос. Я думаю, между статьей и случайным афоризмом. Есть ещё вариант всплывающий, например после 15 секунд на сайте или когда пролистал 3/4 статьи.

**Comment by simlex-titul2005** [comment]
Есть ещё вариант всплывающий, например после 15 секунд на сайте или когда пролистал 3/4 статьи
Худший вариант, который может быть ИМХО. Ты сам остаешься на сайтах, на которых есть такие окна?

**Comment by EugeneKormin** [comment]
Вот поэтому я и склоняюсь к первому

**Comment by simlex-titul2005** [comment]
Блок подписки только на новостях делать? Или на статьях и новостях?

**Comment by EugeneKormin** [comment]
И там и там

**Comment by simlex-titul2005** [comment]
Сделал. Теперь БД можно наполнять подписчиками.
Про рассылку - отедльное issue вроде есть, надо готовить html шаблоны
