### ISSUE TITLE
Поменять картинки в блоке Новости

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#28]
Выполнение необходимо отложить до выполнения https://github.com/EugeneKormin/Game-exe/issues/27

**Comment by simlex-titul2005** [comment]
Как именно? Картинки наверное все-таки должны быть... Можно, например для положительной статьи подсовывать положительную картинку ее игры, для отрицательно - отрицательную и т.д. Для новостей - просто лого игры - но как-то куце выходит. понимаю, что для каждой новости заказывать картинку - затратно...

**Comment by EugeneKormin** [comment]
Я не дописал, сейчас конкурс на отрисовку новых картинок для новостей. Вот их и нужно поставить. А перед текстовыми новостями вставлять те же картинки, но в уменьшенном варианте, а самой новости, если рекламы на эту игру не будет, то ту же картинку, но выполненную горизонтально.

**Comment by simlex-titul2005** [comment]
Актуально?

**Comment by EugeneKormin** [comment]
Я не помню о чем тут, поэтому нет
