### ISSUE TITLE
Можешь подписать статьи подкатегорий, добавить к ним даты, нужно сделать,чтоб было понятно, что это кликабельное меню, а не просто список

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#283]
Как образец можно взять блоки статей и новостей в шапке (цвет необязательно белый). Главное, чтоб было понятно, что это список статей
Блоки в шапке нужно сделать закрытыми снизу

**Comment by simlex-titul2005** [comment]
Блоки в шапке нужно сделать закрытыми снизу
Напиши подробнее - непонятно

**Comment by EugeneKormin** [comment]
![default](https://cloud.githubusercontent.com/assets/16157678/21757774/d547c81a-d687-11e6-84d9-4bdad18021fc.png)

**Comment by simlex-titul2005** [comment]
Сделал. Ctrl+F5 или обновить кеш не забудь, чтоб стили обновились
