### ISSUE TITLE
Добавить rss от Яндекс над подвалом

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#296]
Есть rss от Гугл? Если есть, то его тоже привязать
Добавить rss от Гугл в рубрику "знаете ли вы что", размещенную под rss от Яндекс, из каждой категории будем брать 1 новость
При входе спрашивать город, чтоб отображать новости города пользователя
Каждый раз при входе о чем-нибудь простом спрашивать, данные привязывать к кускам, со временем соберём все данные (более подробно о порядке появления вопросов напишу позже)

**Comment by simlex-titul2005** [comment]
Сделал
