### ISSUE TITLE
Нужно, чтоб картинки норм отображались на смартфонах, потом на планшетах, потом на мобильниках

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#309]
Нужно при любом раскладе картинка сохраняла форму квадрата
![img_0551](https://cloud.githubusercontent.com/assets/16157678/22078862/560e0dfe-de05-11e6-9bca-3072bedae60f.PNG)

**Comment by simlex-titul2005** [comment]
Можеш схематично набросать как должно все выглядеть для разных девайсов?

**Comment by EugeneKormin** [comment]
Варианта два: Сделать прямоугольные статичные картинки, чтоб и для десктопной версии они тоже были прямоугольной. Либо, чтоб они оставались квадратными

**Comment by EugeneKormin** [comment]
либо для смарфонов и мобильников сделать как тут:
![default](https://cloud.githubusercontent.com/assets/16157678/22142664/3a99023a-df4b-11e6-82ac-eff776939a13.png)

**Comment by simlex-titul2005** [comment]
набросай схематично плиз

**Comment by EugeneKormin** [comment]
сек нарисую на листе бумаги

**Comment by EugeneKormin** [comment]
![img_0554](https://cloud.githubusercontent.com/assets/16157678/22142862/a13fc5bc-df43-11e6-8483-4542daa71fbd.JPG)

**Comment by simlex-titul2005** [comment]
http://game-exe.com/news
Сделал, но учти, что изображения должны быть квадратными 
минимальный размер 280 на 280. можно сделать все 300 на 300
