### ISSUE TITLE
Исправить фото авторов в блоке афоризмы, сделать фото авторов и их имена кликабельными

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#311]
Фото авторов не отображаются при нажатии на кнопку следующий
![img_0553](https://cloud.githubusercontent.com/assets/16157678/22079327/26495392-de07-11e6-9057-c71ef01dee8c.PNG)
При клике пользователь должен переходить высказывание автора, но уже на странице афоризмов

**Comment by simlex-titul2005** [comment]
Картинки нормально вроде отображаются... Ссылку сделал
