### ISSUE TITLE
Опять блок афоризмов сломался

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#319]

**Comment by simlex-titul2005** [comment]
опиши проблему

**Comment by EugeneKormin** [comment]
Над планшете не отображаются фотографии
![img_0579](https://cloud.githubusercontent.com/assets/16157678/22234696/ca34d976-e245-11e6-9d8d-8e26ce9bc988.PNG)

**Comment by simlex-titul2005** [comment]
попробуй сбросить кеш, у себя такого не наблюдаю

**Comment by EugeneKormin** [comment]
Хорошо
