### ISSUE TITLE
Блоки сверху-вниз: аннотация, link unit, текст(с квадратным блоком слева сверху), link unit, прямоугольный рекламный блок, подписка, комментарий, популярные статьи

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#341]
![2017-02-11 14_47_56- 2 _ - opera](https://cloud.githubusercontent.com/assets/16157678/23121652/59af073c-f7b5-11e6-8155-3d0a4a30906c.png)

**Comment by simlex-titul2005** [comment]
Сразу под материалом идет блок подписки. Опиши более последовательно структуру страницы материала

**Comment by EugeneKormin** [comment]
текст, рекламный блок, подписка, комментарий

**Comment by EugeneKormin** [comment]
Новое issue тут https://github.com/EugeneKormin/Game-exe/issues/347
