### ISSUE TITLE
добавить прямоугольный рекламный блок между блоками "Проверьте свои знания" и "Геймеру почитать"

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#345]

**Comment by simlex-titul2005** [comment]
На странице не может быть больше 3 рекламных блоков. Необходимо описать расположение всех рекламных блоков для обсуждаемых страниц

**Comment by EugeneKormin** [comment]
Так на главной их 2. 
Первый на "Новостями"
Второй под списком статей

**Comment by simlex-titul2005** [comment]
Сделал
