### ISSUE TITLE
Создать приложение, которое будет мешать копировать контент

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#35]
Единственный вариант - это скачивание, в конце которого автоматически должна ставиться автоматическая ссылка на статью или новость на сайте. Считать кол-во попыток скачать - кол-во обратных ссылок. Нужно узнать сколько людей ставят ссылки, а сколько не ставя ссылки копируют контент

**Comment by simlex-titul2005** [comment]
такое реализовать не получиться. максимум, что можно сделать - это запретить копирования в css... но при таком подходе все равно можно скопировать текст, зная хоть немного браузер

**Comment by EugeneKormin** [comment]
а если после копирования вставлять невидимую ссылку?

**Comment by simlex-titul2005** [comment]
Но ведь ее можно убрать при вставке

**Comment by EugeneKormin** [comment]
ты прав, лучше предложим вступить в партнерску программу
