### ISSUE TITLE
Добавить фавионику

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#36]
Чтобы фавиконка отображалась в результатах поиска, необходимо разместить картинку (файл favicon.ico) размером 16×16 пикселей в корневом каталоге сайта. Предпочтительный формат пиктограммы сайта — ICO, но возможны и другие форматы: GIF, JPEG, PNG и BMP.
Следует убедиться, что при передаче favicon в HTTP-заголовках, отдаваемых веб-сервером, указан корректный тип передаваемых данных — Content-Type:
image/x-icon или image/vnd.microsoft.icon для формата ICO;
image/gif для формата GIF;
image/jpeg для формата JPEG;
image/png для формата PNG;
image/bmp для формата BMP.
Чтобы описать фавиконку в HTML-коде страниц, добавьте следующий код в элемент <head> :
<link rel="icon" href="http://имя сайта/favicon.ico" type="image/x-icon">
или
<link rel="shortcut icon" href="http://имя сайта/favicon.ico" type="image/x-icon">
Если ваша фавиконка находится не в корне, необходимо в поле href указать путь к файлу.
Если фавиконка размещена правильно, и хотя бы одна из страниц вашего сайта показывается в результатах поиска Яндекса, то после посещения сайта роботом она появится в поиске. Информация о роботе, который индексирует пиктограммы, есть в соответствующем разделе помощи.
Скопировано с Яндекс.Помощь

**Comment by simlex-titul2005** [comment]
Сделал
