### ISSUE TITLE
Закрыть от индексации и просмотра всеми кроме нас и СЕОшника

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#41]
Необходимо закрыть доступ к схемам, таблицам, которые получены на основе сбора статистики по посещениям, лайкам, дизлайкам, шерам.
Так же необходимо закрыть страницы-дубликаты, результаты поиска по сайту, статистику посещений, страницы со служебной информацией, баннеры, графики, счетчики, графические информеры и т.п. и тому подобные страницы. Такие страницы не имеют ценности для поисковой системы. Необходимо запретить роботам поисковых сервисов индексирование таких страниц в файле robots.txt.

**Comment by simlex-titul2005** [comment]
Все это делается в robots.txt. Функционал есть
