### ISSUE TITLE
Следить за внешними ссылками

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#43]
1) Попросите партнеров изменить ссылки на более информативные, чтобы они несли больше смысла, чем слова «тут», «здесь», «там», «этот сайт», если необходимо

2) Ссылки, которые используют интернет-СМИ. Если онлайн-СМИ используют информацию с вашего сайта, будет полезно иметь в тексте ссылку с подходящей ключевой фразой.
 
3) Каталоги ссылок: DMOZ, Яндекс.Каталог.
Признаки хорошего каталога:
- Каталог должен быть модерируемым.
- Каталог должен иметь удобную для пользователей навигацию.
- В тематических разделах каталога должны присутствовать ссылки на авторитетные в соответствующей области сайты, сайты компаний-лидеров в своей отрасли.
- Названия и описания сайтов не должны содержать грамматических ошибок, должны быть удобными для восприятия и использования.
- На страницах каталога не должно быть рекламы, мешающей восприятию основного содержимого.

4) Следить за модерацией ссылок с сайта (использовать пост-модерацию)

5) Не пользоваться платными ссылками не при каких обстоятельствах.

p.s. https://yandex.ru/support/webmaster/recommendations/links.xml

**Comment by simlex-titul2005** [comment]
лейбл принять во внимание предлагаю убрать отсюда. заносить только конкретные задачи
