### ISSUE TITLE
Добавить код в левый блок рубрики геймеру почитать (в раскрывающуюся панель с играми

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#44]
Над и под этим кодом нужно добавить ссылку "Подробнее об игре"
Вставить такой код applicationSubCategory
`   <div itemscope itemtype="http://schema.org/SoftwareApplication">
    <div itemprop="applicationSubCategory">MMORPG</div>
    <div itemprop="description">Name of a Game</div>
    <div>Размер клиента:<span itemprop="fileSize">10</span>GB</div>
    <div>Размер игры после установки:<span itemprop="fileSize">25,3</span>GB</div>
    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">Модель распространения:
        <meta itemprop="price" content="0"/>F2P/B2P/P2P</div>
 <div itemprop="price" itemscope itemtype="http://schema.org/Offer">1000 | Базовая:
        <meta itemprop="priceCurrency" content="0"/>RUB</div>
<div itemprop="price" itemscope itemtype="http://schema.org/Offer">2500 | Прем:
        <meta itemprop="priceCurrency" content="0"/>RUB</div>

**Comment by simlex-titul2005** [comment]
Это зачем нужно? Не пойму, какой код добавлять

**Comment by EugeneKormin** [comment]
Этот код упрощает понимание ПС (по крайней мере яндексом) что за контент на странице.
Вставить такой код applicationSubCategory
`   <div itemscope itemtype="http://schema.org/SoftwareApplication">
    <div itemprop="applicationSubCategory">MMORPG</div>
    <div itemprop="description">Name of a Game</div>
    <div>Размер клиента:<span itemprop="fileSize">10</span>GB</div>
    <div>Размер игры после установки:<span itemprop="fileSize">25,3</span>GB</div>
    <div itemprop="offers" itemscope itemtype="http://schema.org/Offer">Модель распространения:
        <meta itemprop="price" content="0"/>F2P/B2P/P2P</div>
 <div itemprop="price" itemscope itemtype="http://schema.org/Offer">1000 | Базовая:
        <meta itemprop="priceCurrency" content="0"/>RUB</div>
<div itemprop="price" itemscope itemtype="http://schema.org/Offer">2500 | Прем:
        <meta itemprop="priceCurrency" content="0"/>RUB</div>

**Comment by EugeneKormin** [comment]
Я в скайп добавил, сюда не добавляется

**Comment by simlex-titul2005** [comment]
Микроразметка
