### ISSUE TITLE
Добавить еще один уровень в "иерархию" категорий в меню игр категории геймеру почитать

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#46]
при выборе игры должны появляться группы, при нажатии на группу подгруппы, при нажатии на которые статьи
Дополнительная подкатегория не должна увеличивать уровень документов. Сейчас у статей он 3

**Comment by simlex-titul2005** [comment]
Это еще актуально?

**Comment by EugeneKormin** [comment]
да

**Comment by simlex-titul2005** [comment]
Сделано
