### ISSUE TITLE
Добавить возможность удалять и переименовывать категории из блока просмотра, убрать слова "Показать... ...в блоке просмотра", оставить только название категории 

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#47]

**Comment by simlex-titul2005** [comment]
изменять само название нельзя, можно изменить только описание типа статьи. иначе конкретные проблемы с маршрутизацией в будущем выскочат. Если нужно изменить тип статей - добавить новый и перепривязать статьи. То название, которое отображается для типа статьи в блоке ГПочитать (ГП) - это описание типа статьи, и оно меняется в админке

**Comment by EugeneKormin** [comment]
Ок, я понял
