### ISSUE TITLE
Добавить верхнюю строку с играми на страницу с 404 ошибкой

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#49]
Так же добавить самую расшариваемую страницу, страницу с лучшим отношением разницы лайков и дизлайков к просмотрам, самую комментируемую статью. Новости по тому же принципу.  Итого 6 текстов.

**Comment by simlex-titul2005** [comment]
Актуально?

**Comment by EugeneKormin** [comment]
да

**Comment by EugeneKormin** [comment]
Дубль
