### ISSUE TITLE
Добавить возможность подгружать существующие теги

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#54]

**Comment by simlex-titul2005** [comment]
Это к чему относиться?

**Comment by EugeneKormin** [comment]
Помнишь ты говорил что на странице для добавления тегов нельзя сразу показывать текущие, но их можно подгружать, вот об этом я и говорил

**Comment by simlex-titul2005** [comment]
Сделано. Теги по-умолчанию задаются, если не указаны в админке
