### ISSUE TITLE
Новая рубрика чёрное/белое

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#56]
С одной стороны, одна точка зрения, с другой - другая. Придумать картинку для выбора на главной, где сейчас новости и блок со статьями. И саму внутреннюю страницу (если она будет)

**Comment by simlex-titul2005** [comment]
Актуально?

**Comment by EugeneKormin** [comment]
Да, позже

**Comment by EugeneKormin** [comment]
Перенёс в другой issue
