### ISSUE TITLE
Тег Keywords

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#6]
Добавить тег keywords в таблицу к тегам desription и title. Вроде, его вес небольшой, но алгоритмы меняются чуть ли не ежемесячно, поэтому лучше, чтоб было. Да и для внутренней оптимизации полезно.

**Comment by simlex-titul2005** [comment]
Теги можно добавить здесь: http://localhost:51077/seoinfo/edit?Id=2

**Comment by EugeneKormin** [comment]
Почему нельзя через меню в админке редактировать?

**Comment by EugeneKormin** [comment]
Почему нельзя через меню в админке редактировать тег keywords?

**Comment by EugeneKormin** [comment]
Тег keywords будет доступен через меню админки когда работы по ней будут завершены?

**Comment by simlex-titul2005** [comment]
Поговорили в skype, можно закрывать
