### ISSUE TITLE
Добавить 2 столбика в блок новостей (между списком новостей и картинками)

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#60]
При наведении появляется возможность развернуть все новости на сайта, все новости по игре

**Comment by simlex-titul2005** [comment]
Можешь рисунок прикрепить?

**Comment by EugeneKormin** [comment]
Это задание не срочное, должна быть техническая возможность это сделать. Диз отрисует, я скину

**Comment by simlex-titul2005** [comment]
Актуально еще?

**Comment by EugeneKormin** [comment]
еще, да, но сначала нарисует диз

**Comment by EugeneKormin** [comment]
Есть отдельная страница по играм
