### ISSUE TITLE
Добавить возможность автоматически редактировать все теги h1, h2, h3 в выбранных статьях, если не получится выбирать статьи, то во всех.

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#61]
У нас есть возможность добавлять рекламу на страницы?

**Comment by simlex-titul2005** [comment]
Редактирование h1 добавлено, только надо слещдить за тем, чтобы h1 в теле не присутствовал, если он задан на странице тегов. h2, h3 и т.д - не гуд выносить для динамического изменения. Они должны регулироваться редактором материала (человеком).
Относительно рекламы - обсудили в скайп. По рекламе - вынеси в отдельный issue

**Comment by EugeneKormin** [comment]
ок
