### ISSUE TITLE
Добавить Надпись "Аннотация к статье" перед текстом.

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#62]
Цветным разделителем нужно отделить аннотацию от основного текста

**Comment by simlex-titul2005** [comment]
Это на детализированных страницах?

**Comment by EugeneKormin** [comment]
да, в статьях на которые переходим из рубрики геймеру почитать

**Comment by simlex-titul2005** [comment]
Сделал
