### ISSUE TITLE
в описание в конце foreword писать дату публикации, версию игры к которой относится статья, имя/ник автора

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#69]
Это должны быть теги
Информация должна дублироваться на странице текста
Информация должна быть видна для ПС

**Comment by simlex-titul2005** [comment]
это на такой странице: http://game-exe.com/articles
или на такой: http://game-exe.com/articles/2016/01/13/4-klassa-bojcov-i-neogranichennyje-varianty-dlja-pobedy
?

**Comment by EugeneKormin** [comment]
И там и там и ПС тоже должны это все видеть

**Comment by simlex-titul2005** [comment]
Сделал
