### ISSUE TITLE
Добавить возможность для пользователя настроить получение комментов и других извещений из соцсетей в личном кабинете на сайте

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#73]
По возможности он должен иметь возможность ответить тут же (если такое вообще возможно)

**Comment by simlex-titul2005** [comment]
Думаю, это нагрузит сайт, т.к. придется проверять профиль по api.

**Comment by EugeneKormin** [comment]
Тогда пока не надо
