### ISSUE TITLE
нужно ли дополнительно настраивать возможность дополнения RSS подписки

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#75]

**Comment by simlex-titul2005** [comment]
Думаю, функционал подписки должен быть в движке. Можно и по rss подписаться. Но наверное, при подписке на что-то пользователю раз в день (или при обновлении интересующего его материала) отправляется материал на почту. А rss так - для сторонних ресурсов

**Comment by simlex-titul2005** [comment]
![default](https://cloud.githubusercontent.com/assets/8962193/21538071/a9e4c96e-cda1-11e6-8550-fe7b4a34c2c0.png)
