### ISSUE TITLE
добавить 404 страницу на сайт

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#77]
![404](https://cloud.githubusercontent.com/assets/16157678/13769076/48ce50da-eac8-11e5-9308-94708ff8d766.jpg)

**Comment by simlex-titul2005** [comment]
Сделал на html-css. Сделаю, чтоб картинку можно было задавать в админке

**Comment by simlex-titul2005** [comment]
404 сделали вроде
