### ISSUE TITLE
Добавить возможность редактирования тега Foreword (назови его "Анонс") для статей и новостей

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#8]

**Comment by simlex-titul2005** [comment]
Для всех материалов помимо Description задается Foreword на странице редактирования материала. Длина 400 символов включая пробелы. При отсутствии Foreword вместо него грузится тело материала (обрезается до 400 символов. без html тегов). Все-таки, Description немного для других целей, тем более, что его (Description) можно задать для любой страницы. В общем, нужно использовать Foreword.

**Comment by EugeneKormin** [comment]
Хорошо.
