### ISSUE TITLE
Добавить парсер курса валют USD/EUR - RUB

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#91]
При переводе иностранных новостей валюта указывается в долларах. А курс он, мягко говоря, не устойчивый, чтоб каждый раз не проверять актуальность цен. Нужно парсить цены с ЦБРФ, цену в рублях сделать кликабельной, а при наведении будет всплывать окно: "Цены обновлены __ минут/часов назад". Он должен переводить из USD/EUR (на выбор) в RUB, наоборот не уверен, что пригодится.
p.s. вот краткое руководство: http://rche.ru/1026_parser-kursov-valyut-na-php.html

**Comment by simlex-titul2005** [comment]
это можно сделать

**Comment by EugeneKormin** [comment]
ок

**Comment by simlex-titul2005** [comment]
Как сделать знаю, а вот где и как это применять на сайте или в админке? Можно пример

**Comment by EugeneKormin** [comment]
стоимость девайса 399$ (145989 рублей) 145989 рублей - курс для вычисления берется из ЦБ РФ

**Comment by simlex-titul2005** [comment]
Этот функционал прямо в теле материала должен быть?

**Comment by EugeneKormin** [comment]
Я не был бы таким категоричным, что мол должен. Он может там быть. Главное, что добавляться должен по 1 клику

**Comment by simlex-titul2005** [comment]
Понял.

**Comment by simlex-titul2005** [comment]
Сделано
