### ISSUE TITLE
Добавить еще 2 рубрики:

### ISSUE THREAD

**Issue by EugeneKormin** [EugeneKormin/Game-exe#94]
1) "Новости корпораций"; 
2) "Новости из виртуального мира".
Картинки будут

**Comment by simlex-titul2005** [comment]
это в меню добавить? или куда?

**Comment by EugeneKormin** [comment]
это будут такие же меню как и раздел новости или рубрика геймеру почитать. С точки зрения иерархии они буду развноценны

**Comment by simlex-titul2005** [comment]
Сделал
